import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import '../../features/transactions/model/expense_model.dart';

class PdfService {
  static Future<void> generateTransactionReport(List<Expense> expenses) async {
    final pdf = pw.Document();
    final now = DateTime.now();
    final dateFormatter = DateFormat('MMM dd, yyyy');

    // Calculate total
    final total = expenses.fold(0.0, (sum, e) => sum + e.amount);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return [
            // Header
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('Expense Report', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                  pw.Text(dateFormatter.format(now), style: const pw.TextStyle(fontSize: 14)),
                ],
              ),
            ),

            pw.SizedBox(height: 20),

            // Summary
            pw.Container(
              alignment: pw.Alignment.centerRight,
              child: pw.Text(
                'Total Spent: \$${total.toStringAsFixed(2)}',
                style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
              ),
            ),

            pw.SizedBox(height: 20),

            // Table
            pw.TableHelper.fromTextArray(
              context: context,
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
              headerDecoration: const pw.BoxDecoration(color: PdfColors.blueGrey900),
              rowDecoration: const pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey300))),
              cellAlignment: pw.Alignment.centerLeft,
              cellAlignments: {
                2: pw.Alignment.centerRight, // Amount column
              },
              data: <List<String>>[
                ['Date', 'Category', 'Amount'],
                ...expenses.map((e) => [
                  dateFormatter.format(e.date),
                  e.category,
                  '\$${e.amount.toStringAsFixed(2)}',
                ]),
              ],
            ),

            pw.Padding(padding: const pw.EdgeInsets.all(10)),

            pw.Footer(
              leading: pw.Text('Generated by SpendLite'),
            ),
          ];
        },
      ),
    );

    // This opens the native share/print dialog
    await Printing.sharePdf(
        bytes: await pdf.save(),
        filename: 'spendlite_report_${now.millisecondsSinceEpoch}.pdf'
    );
  }
}